### ISSUE TITLE
pdftk exited with failure code: 1

### ISSUE THREAD

**Issue by raminious** [tcr/scissors#31]
Hello,
I have an issue with this module. my code is:

```
function splitFiles(splits, filepath) {
  return new Promise((resolve, reject) => {
    const writeStream = fs
      .createWriteStream(filepath)
      .on('error', e => reject(e))

    scissors
      .join(...splits)
      .pdfStream()
      .on('error', (e) => reject(e))
      .on('finish', resolve)
      .pipe(writeStream)
  })
}

try {
   await splitFiles(splits, filepath)
} catch(e) {
   console.log(e)
}
```

the problem is when pdftk can't open one of the files, it kills the server instance instead on throwing a safe error

```
pdftk: Error: Unable to find file.pdftk:
Error: Failed to open PDF file:
   -
Errors encountered.  No output created.
Done.  Input errors, so no output created.
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: pdftk exited with failure code: 1
    at ChildProcess.<anonymous> (/opt/node/project/web/node_modules/scissors/scissors.js:586:21)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
[nodemon] app crashed - waiting for file changes before starting...
```

I can handle this issue by adding `stream.on('error', err => console.log(err))` next to line 564

**Comment by cboulanger** [comment]
Thank you for your report. Can you provide a pull request with this fix?

**Comment by cboulanger** [comment]
Fixed by 9a0b231b428475a2ee1f4bd0f8e8dccdb46e35c4

**Comment by ThunderBoltEngineer** [comment]
Same issue is happening inside Command.prototype._exec function.

I think you should add error handler there as well.

**Comment by cboulanger** [comment]
Can you provide a PR? I am currently not working on scissors, but will be happy to merge fixes.
